// Auto-generated by Supabase MCP from the project schema.
// To regenerate after a migration: ask Claude with the Supabase MCP loaded
// to run `generate_typescript_types` and replace this file.
//
// Do NOT edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      banlist_invites: {
        Row: {
          banlist_id: string
          created_at: string
          created_by: string
          expires_at: string | null
          id: string
          invitee_discord_id: string | null
          max_uses: number | null
          role: Database["public"]["Enums"]["banlist_role"]
          token: string
          used_count: number
        }
        Insert: {
          banlist_id: string
          created_at?: string
          created_by: string
          expires_at?: string | null
          id?: string
          invitee_discord_id?: string | null
          max_uses?: number | null
          role: Database["public"]["Enums"]["banlist_role"]
          token: string
          used_count?: number
        }
        Update: {
          banlist_id?: string
          created_at?: string
          created_by?: string
          expires_at?: string | null
          id?: string
          invitee_discord_id?: string | null
          max_uses?: number | null
          role?: Database["public"]["Enums"]["banlist_role"]
          token?: string
          used_count?: number
        }
        Relationships: [
          {
            foreignKeyName: "banlist_invites_banlist_id_fkey"
            columns: ["banlist_id"]
            isOneToOne: false
            referencedRelation: "banlists"
            referencedColumns: ["id"]
          },
        ]
      }
      banlist_members: {
        Row: {
          added_at: string
          added_by: string | null
          banlist_id: string
          role: Database["public"]["Enums"]["banlist_role"]
          user_id: string
        }
        Insert: {
          added_at?: string
          added_by?: string | null
          banlist_id: string
          role: Database["public"]["Enums"]["banlist_role"]
          user_id: string
        }
        Update: {
          added_at?: string
          added_by?: string | null
          banlist_id?: string
          role?: Database["public"]["Enums"]["banlist_role"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "banlist_members_banlist_id_fkey"
            columns: ["banlist_id"]
            isOneToOne: false
            referencedRelation: "banlists"
            referencedColumns: ["id"]
          },
        ]
      }
      banlists: {
        Row: {
          created_at: string
          id: string
          name: string
          owner_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          name?: string
          owner_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          owner_id?: string
          updated_at?: string
        }
        Relationships: []
      }
      bans: {
        Row: {
          author_id: string | null
          author_name: string
          banlist_id: string
          created_at: string
          faceit_name: string
          id: string
          reason: string
          updated_at: string
        }
        Insert: {
          author_id?: string | null
          author_name: string
          banlist_id: string
          created_at?: string
          faceit_name: string
          id?: string
          reason: string
          updated_at?: string
        }
        Update: {
          author_id?: string | null
          author_name?: string
          banlist_id?: string
          created_at?: string
          faceit_name?: string
          id?: string
          reason?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "bans_banlist_id_fkey"
            columns: ["banlist_id"]
            isOneToOne: false
            referencedRelation: "banlists"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          discord_id: string
          display_name: string
          id: string
        }
        Insert: {
          created_at?: string
          discord_id: string
          display_name: string
          id: string
        }
        Update: {
          created_at?: string
          discord_id?: string
          display_name?: string
          id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      accept_invite: {
        Args: { p_token: string }
        Returns: {
          created_at: string
          id: string
          name: string
          owner_id: string
          updated_at: string
        }
      }
      import_bans: {
        Args: { p_rows: Json }
        Returns: {
          imported: number
          skipped: number
        }[]
      }
    }
    Enums: {
      banlist_role: "viewer" | "editor"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

export const Constants = {
  public: {
    Enums: {
      banlist_role: ["viewer", "editor"],
    },
  },
} as const
