/* PurgeQ — translation strings */
window.PURGEQ_STRINGS = {
  en: {
    nav_features: "Features",
    nav_how: "How it works",
    nav_pricing: "Pricing",
    nav_privacy: "Privacy",
    nav_faq: "FAQ",
    nav_install: "Install",
    nav_github: "GitHub",

    hero_kicker: "// PERSONAL BLACKLIST · FACEIT OVERLAY",
    hero_title: "Never queue with that guy. Again.",
    hero_sub: "Flag cheaters, smurfs and toxic players once. PurgeQ highlights them on every FACEIT card (lobby, match room, party, profile) so you spot the trash before the loading screen.",
    hero_cta_install: "Install for Chrome",
    hero_cta_firefox: "Install for Firefox",
    hero_cta_github: "View on GitHub",
    hero_meta_os: "Chrome · Firefox · Edge · Brave",
    hero_meta_license: "Free tier · EU-hosted · Discord sign-in",

    hero_card_name: "Watashi-",
    hero_card_status: "FLAGGED",
    hero_card_reason: "Wallhack · 3 rounds reviewed",
    hero_card_author: "by Drazy · 2d ago",
    hero_card_clean: "CLEAN",
    hero_card_clean_name: "Komorebi.exe",
    hero_card_clean_meta: "Level 7 · 1842 ELO",

    how_kicker: "// HOW IT WORKS",
    how_title: "Three steps. One Discord login. No server.",
    how_step1_n: "01",
    how_step1_t: "Install the extension",
    how_step1_d: "Grab PurgeQ from the Chrome Web Store or Firefox Add-ons. No server to set up, no API key to configure, already wired to the hosted backend.",
    how_step2_n: "02",
    how_step2_t: "Sign in with Discord",
    how_step2_d: "Open the popup, click Sign in with Discord. One captcha, one OAuth roundtrip, and your personal banlist is ready. Takes about 15 seconds.",
    how_step3_n: "03",
    how_step3_t: "Flag with one click",
    how_step3_d: "Hover any player card on FACEIT, hit Ban, type a reason. They'll be highlighted in red on every page from then on. Go Pro to share your list with teammates.",

    feat_kicker: "// FEATURES",
    feat_title: "Built to make the toxic invisible.",
    feat_1_t: "Visual highlight",
    feat_1_d: "Flagged players get a red glow and red nickname on every card. Hover to see the reason your past self left.",
    feat_2_t: "One-click flag",
    feat_2_d: "Hover, click Ban, type why. Your name is stamped automatically. Unban is one click too.",
    feat_3_t: "Live sync",
    feat_3_d: "New player joins your lobby? PurgeQ checks the server in real time. Your teammates' flags appear within seconds.",
    feat_4_t: "Team-shared lists",
    feat_4_d: "Share your banlist with up to 5 teammates via invite link. Give viewer or editor access. Everyone's highlights stay in sync. Pro feature.",
    feat_5_t: "Import / Export",
    feat_5_d: "Bulk-add from JSON or CSV. Export anytime for backup. Migrate from another tool, or seed your team with a starter list.",
    feat_6_t: "Works offline",
    feat_6_d: "The extension caches the last list locally. Highlights still show even when you're offline.",

    pricing_kicker: "// PRICING",
    pricing_title: "Free forever. Pro when you need a team.",
    pricing_free_name: "Free",
    pricing_free_price: "$0",
    pricing_free_period: "forever",
    pricing_free_cta: "Install free",
    pricing_free_f1: "Up to 250 flagged players",
    pricing_free_f2: "Sync across all your devices",
    pricing_free_f3: "Import / export anytime",
    pricing_free_f4: "Chrome, Firefox, Edge, Brave",
    pricing_pro_name: "Pro",
    pricing_pro_price: "$3",
    pricing_pro_period: "one time",
    pricing_pro_cta: "Go Pro",
    pricing_pro_f1: "Unlimited flagged players",
    pricing_pro_f2: "Shared team workspace, up to 5 seats",
    pricing_pro_f3: "Per-member attribution on every ban",

    privacy_kicker: "// PRIVACY",
    privacy_title: "EU-hosted. GDPR by default.",
    privacy_lead: "Hosted on Supabase Frankfurt and Cloudflare EU. No email collected, no analytics, no third-party trackers. Export or delete everything in two clicks from the popup.",
    privacy_p1_t: "EU-only",
    privacy_p1_d: "Your profile and banlist sit in Supabase Frankfurt under DPA. Cloudflare handles the static landing and bot check, also EU. No transfers to US servers in normal use.",
    privacy_p2_t: "No tracking",
    privacy_p2_d: "No analytics SDK, no telemetry, no tracking pixels, not in the extension nor on this page. The only network calls are to Supabase, Cloudflare and Discord OAuth.",
    privacy_p3_t: "GDPR built-in",
    privacy_p3_d: "Settings > Your data: Export gives you a JSON dump of everything we store. Delete account wipes it for good. No email to write, no form to fill.",
    privacy_p4_t: "No FACEIT account access",
    privacy_p4_d: "PurgeQ never reads your FACEIT credentials, match history or chat. The extension paints names on the FACEIT pages you already see, that's it.",

    faq_kicker: "// FAQ",
    faq_title: "Questions, briefly.",
    faq_q1: "Is this against FACEIT's ToS?",
    faq_a1: "PurgeQ is a purely visual client-side overlay. It does not interact with FACEIT's API, does not automate matchmaking, does not modify pages for other users. It reads what your browser already displays and adds a colored border. That said: you are responsible for how you use it.",
    faq_q2: "Does it dodge players for me?",
    faq_a2: "No. PurgeQ flags. You choose what to do: leave, party with someone else, or just go in informed. We do not interfere with the queue.",
    faq_q3: "What is the difference between Free and Pro?",
    faq_a3: "Free gives you up to 250 flagged players, synced across your devices. Pro ($3 one time) removes that cap and adds team sharing: invite up to 5 teammates via a link, with viewer or editor roles.",
    faq_q4: "What happens to my list if I'm offline?",
    faq_a4: "The extension caches the last fetched list locally. Highlights keep showing. New flags you add while offline will sync automatically when you reconnect.",
    faq_q5: "Can it pull lists from a public cheater database?",
    faq_a5: "Not yet, by design. PurgeQ is your call, not a crowd-sourced verdict. The import tab accepts any JSON or CSV though, so feeding it from another source is trivial.",
    faq_q6: "Why orange?",
    faq_a6: "Because flagged players are red, and orange is the only color that survives both being next to red AND being on a dark UI without looking like a fire alarm.",

    footer_tagline: "Personal blacklist for FACEIT. Free to start, Pro for teams.",
    footer_install: "Install",
    footer_resources: "Resources",
    footer_chrome: "Chrome Web Store",
    footer_firefox: "Firefox Add-ons",
    footer_release: "Latest release",
    footer_docs: "Documentation",
    footer_arch: "Architecture",
    footer_privacy_doc: "Privacy policy",
    footer_legal: "© 2026 PurgeQ · MIT License · Not affiliated with FACEIT.",

    cta_band_kicker: "// READY",
    cta_band_title: "Stop seeing them. Start winning more.",
    cta_band_sub: "Sixty seconds to install. Free forever.",

    tweaks_title: "Tweaks",
    tweaks_logo: "Logo style",
    tweaks_logo_shield: "Shield + wordmark",
    tweaks_logo_wordmark: "Wordmark only",
    tweaks_logo_mono: "Monogram + wordmark"
  },
  fr: {
    nav_features: "Fonctionnalités",
    nav_how: "Comment ca marche",
    nav_pricing: "Tarifs",
    nav_privacy: "Confidentialite",
    nav_faq: "FAQ",
    nav_install: "Installer",
    nav_github: "GitHub",

    hero_kicker: "// BLACKLIST PERSO · OVERLAY FACEIT",
    hero_title: "Ne joue plus jamais avec ce type.",
    hero_sub: "Marque les cheaters, smurfs et joueurs toxiques une seule fois. PurgeQ les surligne sur chaque carte FACEIT (lobby, match room, party, profil) pour reperer le dechet avant l'ecran de chargement.",
    hero_cta_install: "Installer pour Chrome",
    hero_cta_firefox: "Installer pour Firefox",
    hero_cta_github: "Voir sur GitHub",
    hero_meta_os: "Chrome · Firefox · Edge · Brave",
    hero_meta_license: "Gratuit · Heberge UE · Login Discord",

    hero_card_name: "Watashi-",
    hero_card_status: "BANNI",
    hero_card_reason: "Wallhack · 3 manches revues",
    hero_card_author: "par Drazy · il y a 2j",
    hero_card_clean: "CLEAN",
    hero_card_clean_name: "Komorebi.exe",
    hero_card_clean_meta: "Niveau 7 · 1842 ELO",

    how_kicker: "// COMMENT CA MARCHE",
    how_title: "Trois etapes. Un login Discord. Aucun serveur.",
    how_step1_n: "01",
    how_step1_t: "Installe l'extension",
    how_step1_d: "Recupere PurgeQ sur le Chrome Web Store ou Firefox Add-ons. Pas de serveur a configurer, pas de cle API, deja branche sur le backend heberge.",
    how_step2_n: "02",
    how_step2_t: "Connecte-toi via Discord",
    how_step2_d: "Ouvre la popup, clique Sign in with Discord. Un captcha, un OAuth, ta banlist personnelle est prete. Environ 15 secondes.",
    how_step3_n: "03",
    how_step3_t: "Ban en un clic",
    how_step3_d: "Survole une carte joueur sur FACEIT, clique Ban, ecris la raison. Il sera surligne en rouge partout. Passe en Pro pour partager ta liste avec des coequipiers.",

    feat_kicker: "// FONCTIONNALITES",
    feat_title: "Concu pour rendre les toxiques invisibles.",
    feat_1_t: "Surlignage visuel",
    feat_1_d: "Les joueurs bannis ont un halo rouge et pseudo rouge sur chaque carte. Survole pour voir la raison que ton toi-passe a laissee.",
    feat_2_t: "Ban en un clic",
    feat_2_d: "Survole, clique Ban, ecris pourquoi. Ton nom est stampe automatiquement. Le unban est aussi en un clic.",
    feat_3_t: "Sync en direct",
    feat_3_d: "Un joueur rejoint ton lobby ? PurgeQ interroge le serveur en temps reel. Les bans de tes potes apparaissent en quelques secondes.",
    feat_4_t: "Listes partagees",
    feat_4_d: "Partage ta banlist avec jusqu'a 5 coequipiers via lien d'invitation. Acces viewer ou editor. Les surlignages de tout le monde restent synchro. Fonctionnalite Pro.",
    feat_5_t: "Import / Export",
    feat_5_d: "Bulk-add depuis JSON ou CSV. Export a tout moment pour backup. Migre depuis un autre outil, ou seed ta team avec une liste de depart.",
    feat_6_t: "Marche offline",
    feat_6_d: "L'extension cache la derniere liste localement. Le surlignage continue meme hors ligne.",

    pricing_kicker: "// TARIFS",
    pricing_title: "Gratuit pour toujours. Pro pour les equipes.",
    pricing_free_name: "Gratuit",
    pricing_free_price: "0 $",
    pricing_free_period: "pour toujours",
    pricing_free_cta: "Installer",
    pricing_free_f1: "Jusqu'a 250 joueurs flagges",
    pricing_free_f2: "Sync sur tous tes appareils",
    pricing_free_f3: "Import / export a tout moment",
    pricing_free_f4: "Chrome, Firefox, Edge, Brave",
    pricing_pro_name: "Pro",
    pricing_pro_price: "3 $",
    pricing_pro_period: "une seule fois",
    pricing_pro_cta: "Passer Pro",
    pricing_pro_f1: "Joueurs flagges illimites",
    pricing_pro_f2: "Espace d'equipe partage, jusqu'a 5 membres",
    pricing_pro_f3: "Attribution par membre sur chaque ban",

    privacy_kicker: "// CONFIDENTIALITE",
    privacy_title: "Heberge en UE. RGPD par defaut.",
    privacy_lead: "Heberge sur Supabase Francfort et Cloudflare UE. Pas d'email collecte, pas d'analytics, pas de tracker tiers. Export ou suppression en deux clics depuis la popup.",
    privacy_p1_t: "UE uniquement",
    privacy_p1_d: "Ton profil et ta banlist vivent dans Supabase Francfort sous DPA. Cloudflare heberge la landing et la verif anti-bot, aussi UE. Aucun transfert vers les US en usage normal.",
    privacy_p2_t: "Aucun tracking",
    privacy_p2_d: "Aucun SDK analytics, aucune telemetrie, aucun pixel de tracking, ni dans l'extension ni sur cette page. Les seuls appels reseau vont a Supabase, Cloudflare et Discord OAuth.",
    privacy_p3_t: "RGPD natif",
    privacy_p3_d: "Settings > Your data : Export te donne un JSON de tout ce qu'on stocke. Delete account efface tout, definitivement. Pas d'email a ecrire, pas de formulaire.",
    privacy_p4_t: "Pas d'acces au compte FACEIT",
    privacy_p4_d: "PurgeQ ne lit jamais tes identifiants FACEIT, ton historique de match ou ton chat. L'extension peint des pseudos sur les pages FACEIT que tu vois deja, c'est tout.",

    faq_kicker: "// FAQ",
    faq_title: "Questions, vite fait.",
    faq_q1: "C'est contre les ToS de FACEIT ?",
    faq_a1: "PurgeQ est un overlay purement visuel cote client. Il n'interagit pas avec l'API FACEIT, n'automatise pas le matchmaking, ne modifie pas les pages pour les autres utilisateurs. Il lit ce que ton navigateur affiche deja et ajoute une bordure coloree. Ceci dit : tu es responsable de l'usage que tu en fais.",
    faq_q2: "Est-ce que ca dodge les joueurs pour moi ?",
    faq_a2: "Non. PurgeQ marque. C'est toi qui decides : partir, partyer avec quelqu'un d'autre, ou y aller informe. On n'interfere pas avec la file.",
    faq_q3: "Quelle est la difference entre Gratuit et Pro ?",
    faq_a3: "Le plan Gratuit permet jusqu'a 250 joueurs flagges, synchro sur tes appareils. Pro (3 $ une seule fois) supprime cette limite et ajoute le partage d'equipe : invite jusqu'a 5 coequipiers via un lien, avec des roles viewer ou editor.",
    faq_q4: "Que se passe-t-il si je suis hors ligne ?",
    faq_a4: "L'extension cache la derniere liste recuperee localement. Le surlignage continue. Les nouveaux bans ajoutes hors ligne se synchronisent automatiquement a la reconnexion.",
    faq_q5: "Peut-on importer une base publique de cheaters ?",
    faq_a5: "Pas encore, et c'est volontaire. PurgeQ est ton appel, pas un verdict crowd-source. Mais l'onglet import accepte n'importe quel JSON ou CSV, donc le brancher sur une autre source est trivial.",
    faq_q6: "Pourquoi orange ?",
    faq_a6: "Parce que les joueurs flagges sont rouges, et l'orange est la seule couleur qui survit a la fois a cote du rouge ET sur une UI sombre sans ressembler a une alarme incendie.",

    footer_tagline: "Blacklist personnelle pour FACEIT. Gratuit, heberge UE, open source.",
    footer_install: "Installer",
    footer_resources: "Ressources",
    footer_chrome: "Chrome Web Store",
    footer_firefox: "Firefox Add-ons",
    footer_release: "Derniere release",
    footer_docs: "Documentation",
    footer_arch: "Architecture",
    footer_privacy_doc: "Politique de confidentialite",
    footer_legal: "© 2026 PurgeQ · Licence MIT · Non affilie a FACEIT.",

    cta_band_kicker: "// PRET",
    cta_band_title: "Arrete de les voir. Commence a gagner.",
    cta_band_sub: "Soixante secondes pour installer. Gratuit pour toujours.",

    tweaks_title: "Tweaks",
    tweaks_logo: "Style du logo",
    tweaks_logo_shield: "Bouclier + nom",
    tweaks_logo_wordmark: "Nom seul",
    tweaks_logo_mono: "Monogramme + nom"
  }
};
