/* PurgeQ — translation strings */
window.PURGEQ_STRINGS = {
  en: {
    nav_features: "Features",
    nav_how: "How it works",
    nav_privacy: "Privacy",
    nav_faq: "FAQ",
    nav_install: "Install",
    nav_github: "GitHub",

    hero_kicker: "// PERSONAL BLACKLIST · FACEIT OVERLAY",
    hero_title: "Never queue with that guy. Again.",
    hero_sub: "Flag cheaters, smurfs and toxic players once. PurgeQ highlights them directly on every FACEIT card — lobby, match room, party, profile — so you spot the trash before the loading screen.",
    hero_cta_install: "Install for Chrome",
    hero_cta_github: "View on GitHub",
    hero_meta_os: "Chrome · Firefox · Edge · Brave",
    hero_meta_license: "MIT · EU-hosted · Discord sign-in",

    hero_card_name: "Watashi-",
    hero_card_status: "FLAGGED",
    hero_card_reason: "Wallhack · 3 rounds reviewed",
    hero_card_author: "by Drazy · 2d ago",
    hero_card_clean: "CLEAN",
    hero_card_clean_name: "Komorebi.exe",
    hero_card_clean_meta: "Level 7 · 1842 ELO",

    how_kicker: "// HOW IT WORKS",
    how_title: "Three steps. No accounts. No telemetry.",
    how_step1_n: "01",
    how_step1_t: "Install the extension",
    how_step1_d: "Grab PurgeQ from the Chrome Web Store or addons.mozilla.org. No accounts to create, no server URLs to type — it's already wired to the hosted backend.",
    how_step2_n: "02",
    how_step2_t: "Sign in with Discord",
    how_step2_d: "Open the popup, click Sign in with Discord. One captcha, one OAuth roundtrip, and your personal banlist is ready. Takes about 15 seconds.",
    how_step3_n: "03",
    how_step3_t: "Flag with one click",
    how_step3_d: "Hover any player card on FACEIT, hit Ban, type a reason. They'll be highlighted in red on every page from then on — for you and any friend you invite to your banlist.",

    feat_kicker: "// FEATURES",
    feat_title: "Built to make the toxic invisible.",
    feat_1_t: "Visual highlight",
    feat_1_d: "Flagged players get a red glow + red nickname on every card. Hover to see the reason your past self left.",
    feat_2_t: "One-click flag",
    feat_2_d: "Hover, click Ban, type why. Your name is stamped automatically. Unban is one click too.",
    feat_3_t: "Live sync",
    feat_3_d: "New player joins your lobby? PurgeQ hits the server in real time. Your teammates' flags appear within seconds.",
    feat_4_t: "Team-shared lists",
    feat_4_d: "Point several extensions at the same server with the same key. Everyone sees the same list, edits propagate instantly.",
    feat_5_t: "Import / Export",
    feat_5_d: "Bulk-add from JSON or CSV. Export anytime for backup. Migrate from another tool, or seed your team with a starter list.",
    feat_6_t: "Works offline",
    feat_6_d: "The extension caches the last list locally. Highlights still show even if your server is asleep.",

    privacy_kicker: "// PRIVACY",
    privacy_title: "EU-hosted. GDPR by default.",
    privacy_lead: "Hosted on Supabase Frankfurt + Cloudflare EU. No email collected, no analytics, no third-party trackers. Export or delete everything in two clicks from the popup.",
    privacy_p1_t: "EU-only",
    privacy_p1_d: "Your profile and banlist sit in Supabase Frankfurt under DPA. Cloudflare handles the static landing + bot check, also EU. No transfers to US servers in normal use.",
    privacy_p2_t: "No tracking",
    privacy_p2_d: "No analytics SDK, no telemetry, no tracking pixels — neither in the extension nor on this page. The only network calls are to Supabase, Cloudflare and Discord OAuth.",
    privacy_p3_t: "GDPR built-in",
    privacy_p3_d: "Settings → Your data: Export gives you a JSON dump of everything we store; Delete account wipes it for good. No email to write, no form to fill.",
    privacy_p4_t: "No FACEIT account access",
    privacy_p4_d: "PurgeQ never reads your FACEIT credentials, match history or chat. The extension paints names on the FACEIT pages you already see, that's it.",

    faq_kicker: "// FAQ",
    faq_title: "Questions, briefly.",
    faq_q1: "Is this against FACEIT's ToS?",
    faq_a1: "PurgeQ is a purely visual client-side overlay. It does not interact with FACEIT's API, does not automate matchmaking, does not modify pages for other users. It reads what your browser already displays and adds a colored border. That said: you are responsible for how you use it.",
    faq_q2: "Does it dodge players for me?",
    faq_a2: "No. PurgeQ flags. You choose what to do about it — leave, party with someone else, or just go in informed. We do not interfere with the queue.",
    faq_q3: "Do I need to expose my server to the internet?",
    faq_a3: "Only if you want friends on other networks to share your list. For solo use, localhost is fine. For LAN teammates, your local IP is fine. For internet sharing, put Caddy or Nginx in front and use the multi-tenant Discord flow.",
    faq_q4: "What happens to my list if the server is down?",
    faq_a4: "The extension caches the last fetched list locally. Highlights keep showing. Adding new flags is paused until the server is back — they queue and retry.",
    faq_q5: "Can it pull lists from a public cheater database?",
    faq_a5: "Not yet, by design. PurgeQ is your call, not a crowd-sourced verdict. The import endpoint accepts any JSON / CSV though, so feeding it from another source is trivial.",
    faq_q6: "Why orange?",
    faq_a6: "Because flagged players are red, and orange is the only color that survives both being next to red AND being on a dark UI without looking like a fire alarm.",

    footer_tagline: "Personal blacklist for FACEIT. Free, EU-hosted, open source.",
    footer_install: "Install",
    footer_resources: "Resources",
    footer_chrome: "Chrome Web Store",
    footer_firefox: "Firefox Add-ons",
    footer_release: "Latest release",
    footer_docs: "Documentation",
    footer_arch: "Architecture",
    footer_privacy_doc: "Privacy policy",
    footer_legal: "© 2026 PurgeQ · MIT License · Not affiliated with FACEIT.",

    cta_band_kicker: "// READY",
    cta_band_title: "Stop seeing them. Start winning more.",
    cta_band_sub: "Sixty seconds to install. Forever to enjoy.",

    tweaks_title: "Tweaks",
    tweaks_logo: "Logo style",
    tweaks_logo_shield: "Shield + wordmark",
    tweaks_logo_wordmark: "Wordmark only",
    tweaks_logo_mono: "Monogram + wordmark"
  },
  fr: {
    nav_features: "Fonctionnalités",
    nav_how: "Comment ça marche",
    nav_privacy: "Confidentialité",
    nav_faq: "FAQ",
    nav_install: "Installer",
    nav_github: "GitHub",

    hero_kicker: "// BLACKLIST PERSO · OVERLAY FACEIT",
    hero_title: "Ne joue plus jamais avec ce type.",
    hero_sub: "Marque les cheaters, smurfs et joueurs toxiques une seule fois. PurgeQ les surligne directement sur chaque carte FACEIT — lobby, match room, party, profil — pour repérer le déchet avant l'écran de chargement.",
    hero_cta_install: "Installer pour Chrome",
    hero_cta_github: "Voir sur GitHub",
    hero_meta_os: "Chrome · Firefox · Edge · Brave",
    hero_meta_license: "MIT · Hébergé UE · Login Discord",

    hero_card_name: "Watashi-",
    hero_card_status: "BANNI",
    hero_card_reason: "Wallhack · 3 manches revues",
    hero_card_author: "par Drazy · il y a 2j",
    hero_card_clean: "CLEAN",
    hero_card_clean_name: "Komorebi.exe",
    hero_card_clean_meta: "Niveau 7 · 1842 ELO",

    how_kicker: "// COMMENT ÇA MARCHE",
    how_title: "Trois étapes. Aucun compte. Aucun tracking.",
    how_step1_n: "01",
    how_step1_t: "Installe l'extension",
    how_step1_d: "Récupère PurgeQ sur le Chrome Web Store ou addons.mozilla.org. Pas de compte à créer, pas d'URL serveur à taper — c'est déjà branché sur le backend hébergé.",
    how_step2_n: "02",
    how_step2_t: "Connecte-toi via Discord",
    how_step2_d: "Ouvre la popup, clique Sign in with Discord. Un captcha, un OAuth, ta banlist personnelle est prête. Environ 15 secondes.",
    how_step3_n: "03",
    how_step3_t: "Ban en un clic",
    how_step3_d: "Survole une carte joueur sur FACEIT, clique Ban, écris la raison. Il sera surligné en rouge partout — pour toi et toute personne que tu invites sur ta banlist.",

    feat_kicker: "// FONCTIONNALITÉS",
    feat_title: "Conçu pour rendre les toxiques invisibles.",
    feat_1_t: "Surlignage visuel",
    feat_1_d: "Les joueurs bannis ont un halo rouge + pseudo rouge sur chaque carte. Survole pour voir la raison que ton toi-passé a laissée.",
    feat_2_t: "Ban en un clic",
    feat_2_d: "Survole, clique Ban, écris pourquoi. Ton nom est stamped automatiquement. Le unban est aussi en un clic.",
    feat_3_t: "Sync en direct",
    feat_3_d: "Un joueur rejoint ton lobby ? PurgeQ interroge le serveur en temps réel. Les bans de tes potes apparaissent en quelques secondes.",
    feat_4_t: "Listes partagées",
    feat_4_d: "Pointe plusieurs extensions sur le même serveur avec la même clé. Tout le monde voit la même liste, les éditions se propagent instantanément.",
    feat_5_t: "Import / Export",
    feat_5_d: "Bulk-add depuis JSON ou CSV. Export à tout moment pour backup. Migre depuis un autre outil, ou seed ta team avec une liste de départ.",
    feat_6_t: "Marche offline",
    feat_6_d: "L'extension cache la dernière liste localement. Le surlignage continue même si ton serveur dort.",

    privacy_kicker: "// CONFIDENTIALITÉ",
    privacy_title: "Hébergé en UE. RGPD par défaut.",
    privacy_lead: "Hébergé sur Supabase Francfort + Cloudflare UE. Pas d'email collecté, pas d'analytics, pas de tracker tiers. Export ou suppression en deux clics depuis la popup.",
    privacy_p1_t: "UE uniquement",
    privacy_p1_d: "Ton profil et ta banlist vivent dans Supabase Francfort sous DPA. Cloudflare héberge la landing + la vérif anti-bot, aussi UE. Aucun transfert vers les US en usage normal.",
    privacy_p2_t: "Aucun tracking",
    privacy_p2_d: "Aucun SDK analytics, aucune télémétrie, aucun pixel de tracking — ni dans l'extension, ni sur cette page. Les seuls appels réseau vont à Supabase, Cloudflare et Discord OAuth.",
    privacy_p3_t: "RGPD natif",
    privacy_p3_d: "Settings → Your data : Export te donne un JSON de tout ce qu'on stocke ; Delete account efface tout, définitivement. Pas d'email à écrire, pas de formulaire.",
    privacy_p4_t: "Pas d'accès au compte FACEIT",
    privacy_p4_d: "PurgeQ ne lit jamais tes identifiants FACEIT, ton historique de match ou ton chat. L'extension peint des pseudos sur les pages FACEIT que tu vois déjà, c'est tout.",

    faq_kicker: "// FAQ",
    faq_title: "Questions, vite fait.",
    faq_q1: "C'est contre les ToS de FACEIT ?",
    faq_a1: "PurgeQ est un overlay purement visuel côté client. Il n'interagit pas avec l'API FACEIT, n'automatise pas le matchmaking, ne modifie pas les pages pour les autres utilisateurs. Il lit ce que ton navigateur affiche déjà et ajoute une bordure colorée. Ceci dit : tu es responsable de l'usage que tu en fais.",
    faq_q2: "Est-ce que ça dodge les joueurs pour moi ?",
    faq_a2: "Non. PurgeQ marque. C'est toi qui décides quoi faire — partir, partyer avec quelqu'un d'autre, ou y aller informé. On n'interfère pas avec la file.",
    faq_q3: "Faut-il exposer mon serveur sur Internet ?",
    faq_a3: "Seulement si tu veux que des potes sur d'autres réseaux partagent ta liste. Pour un usage solo, localhost suffit. Pour des coéquipiers LAN, ton IP locale suffit. Pour partager sur Internet, mets Caddy ou Nginx devant et utilise le flow multi-tenant Discord.",
    faq_q4: "Que se passe-t-il si le serveur tombe ?",
    faq_a4: "L'extension cache la dernière liste récupérée localement. Le surlignage continue. L'ajout de nouveaux bans est en pause jusqu'au retour du serveur — ils queuent et retentent.",
    faq_q5: "Peut-on importer une base publique de cheaters ?",
    faq_a5: "Pas encore, et c'est volontaire. PurgeQ est ton appel, pas un verdict crowd-sourcé. Mais l'endpoint d'import accepte n'importe quel JSON / CSV, donc le brancher sur une autre source est trivial.",
    faq_q6: "Pourquoi orange ?",
    faq_a6: "Parce que les joueurs flagués sont rouges, et l'orange est la seule couleur qui survit à la fois à côté du rouge ET sur une UI sombre sans ressembler à une alarme incendie.",

    footer_tagline: "Blacklist personnelle pour FACEIT. Gratuit, hébergé UE, open source.",
    footer_install: "Installer",
    footer_resources: "Ressources",
    footer_chrome: "Chrome Web Store",
    footer_firefox: "Firefox Add-ons",
    footer_release: "Dernière release",
    footer_docs: "Documentation",
    footer_arch: "Architecture",
    footer_privacy_doc: "Politique de confidentialité",
    footer_legal: "© 2026 PurgeQ · Licence MIT · Non affilié à FACEIT.",

    cta_band_kicker: "// PRÊT",
    cta_band_title: "Arrête de les voir. Commence à gagner.",
    cta_band_sub: "Soixante secondes pour installer. À vie pour en profiter.",

    tweaks_title: "Tweaks",
    tweaks_logo: "Style du logo",
    tweaks_logo_shield: "Bouclier + nom",
    tweaks_logo_wordmark: "Nom seul",
    tweaks_logo_mono: "Monogramme + nom"
  }
};
